# Generated by Django 4.1.3 on 2022-11-26 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placetypes',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='placetypes',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placetypes')),
            ],
        ),
    ]
