# Generated by Django 4.1.3 on 2022-11-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_title_placetypes_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='place_type',
        ),
    ]
