# Generated by Django 4.1.3 on 2022-11-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_type_place_place_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placetypes',
            name='type',
        ),
    ]
