# Generated by Django 4.1.3 on 2022-12-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_placetypes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
