# Generated by Django 4.1.3 on 2022-12-02 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
